### ISSUE TITLE
想问问大佬，您的首页和wiki界面怎么弄的呀，觉得特别符合自己的审美，想学习一下～

### ISSUE THREAD

**Issue by feelheart7** [xaoxuu/xaoxuu.github.io#4]
想问问大佬，您的首页和wiki界面怎么弄的呀，觉得特别符合自己的审美，想学习一下～

**Comment by xaoxuu** [comment]
主题：https://github.com/xaoxuu/hexo-theme-vuex
这个不提供技术支持，自己摸索吧。
